//
//  AppConstants.swift
//  AIEnglishSentences
//
//  Created by mert alp on 26.12.2024.
//

import UIKit

struct AppConstants {
    
    struct URLs {

        static let appUrl = "https://apps.apple.com/tr/app/iq-test/id6670162878?l=tr"
        static let iqTestAppURLScheme = "iqtest://"
        static let iqTestAppStoreURL = "https://apps.apple.com/tr/app/iq-test/id6670162878?l=tr"
    }
    
    static let privacyPolicy =
        """
        Privacy Policy

        1. Introduction
        Welcome to the AI-Lex application! Your privacy is critically important to us. This Privacy Policy explains how we collect, use, and share information about you when you use our application and services.

        2. Information We Collect

        2.1 Personal Information
        We may collect the following personal information:
            •    Name and Email Address: Collected during authentication via Google or Apple.
            •    User ID: A unique identifier generated during account creation.

        2.2 Usage Data
        We collect information about how you interact with the app, including:
            •    Screen views, button clicks, and other in-app activities.
            •    Analytics data to improve user experience (via Firebase Analytics).

        2.3 Payment Information
        We use RevenueCat for managing in-app purchases. RevenueCat handles all payment processes securely, and we do not store or process your credit card details.

        2.4 Crash and Performance Data
        To ensure a stable and reliable app, we collect:
            •    Crash reports (via Firebase Crashlytics).
            •    Performance metrics (e.g., app launch time, energy usage) through Firebase Performance Monitoring.

        2.5 Content Data
        When you use the app to generate sentences, we may send your input to OpenAI for processing. The sentences generated by OpenAI are not stored by us.

        3. How We Use Your Information
        We use the information collected to:
            •    Authenticate users and secure access to the app.
            •    Improve app performance and user experience.
            •    Deliver personalized content and learning recommendations.
            •    Manage in-app subscriptions and purchases.

        4. Data Sharing
        We do not sell your data to third parties. However, we share data with:
            •    Firebase for analytics, authentication, and crash reporting.
            •    OpenAI for processing user-generated prompts.
            •    RevenueCat for managing in-app purchases.

        All third-party services comply with their respective privacy policies:
            •    Firebase Privacy Policy
            •    OpenAI Privacy Policy
            •    RevenueCat Privacy Policy

        5. Data Retention
        We retain your data for as long as it is necessary to provide our services and comply with legal obligations. You can request account deletion at any time by contacting us.

        6. User Rights
        As a user, you have the following rights:
            •    Access and review your personal data.
            •    Request correction or deletion of your data.
            •    Withdraw consent for data processing.

        7. Security
        We implement industry-standard security measures to protect your data, including:
            •    Encrypted communication between the app and our servers.
            •    Secure handling of payment data via RevenueCat.

        8. Changes to This Privacy Policy
        We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date.

        9. Contact Us
        If you have questions about this Privacy Policy, please contact us:
            •    Support Email: mertalp010@gmail.com
         m
        """
    
    
    static let myApps: [AppModel] = [
        AppModel(appIcon: UIImage.appImage(.iqTestLogo)!, appName: "IQ Test", appDescription: "The IQ Test application allows you to effectively test your mental skills and quickly evaluate your progress. Complete your tests in just 5 minutes and discover your IQ level while tracking your improvement."),
        AppModel(appIcon: UIImage.appImage(.appIcon)!, appName: "AILex", appDescription: "AILex helps you improve your English skills by generating sentences using AI-provided words. Practice listening to these sentences and enhance your vocabulary and comprehension. In just a few minutes a day, boost your confidence in English while tracking your progress and mastering the language."),
       
    ]
    
    static let baseDeviceHeight:  CGFloat = 812.0
    static let baseDeviceWidth: CGFloat = 375.0
    
}
